export const packageCategories = [
    {
        id: "website-design",
        label: "Website Design",
        packages: [
            {
                id: "website-design-starter",
                sku: "WEBSITE DESIGN STARTER",
                title: "Starter Package",
                price: "$299",
                features: [
                    "Up to 3 Pages",
                    "Custom Responsive Web Design",
                    "Mobile & Tablet Friendly",
                    "Contact Form",
                    "Social Media Links",
                    "1 Round of Revisions",
                ],
            },
            {
                id: "website-design-business",
                sku: "WEBSITE DESIGN BUSINESS",
                title: "Business Package",
                price: "$399",
                features: [
                    "Everything in the Starter Package",
                    "Up to 7 Pages",
                    "Custom UI Design",
                    "Additional Contact/Inquiry Forms",
                    "Image Gallery",
                    "Basic Animations & Hover Effects",
                    "Enhanced Performance Optimization",
                    "3 Rounds of Revisions",
                ],
            },
            {
                id: "website-design-premium",
                sku: "WEBSITE DESIGN PREMIUM",
                title: "Premium Package",
                price: "$599",
                features: [
                    "Everything in the Business Package",
                    "Up to 12 Pages",
                    "Premium Custom Design",
                    "Advanced UI/UX Enhancements",
                    "Interactive Sections",
                    "Advanced Forms",
                    "Cross-Browser Compatibility Testing",
                    "Priority Support During Development",
                    "5 Rounds of Revisions",
                ],
            },
        ],
    },
    {
        id: "cms-development",
        label: "CMS Development",
        packages: [
            {
                id: "cms-development-starter",
                sku: "CMS DEVELOPMENT STARTER",
                title: "Starter CMS",
                price: "$299",
                features: [
                    "CMS Installation & Setup",
                    "Theme Configuration",
                    "Up to 5 Pages",
                    "Contact Form Setup",
                    "Basic Plugin Installation",
                    "Mobile Responsive Configuration",
                    "Basic Security Setup",
                    "Speed Optimization",
                    "1 Round of Revisions",
                ],
            },
            {
                id: "cms-development-business",
                sku: "CMS_DEVELOPMENT_BUSINESS",
                title: "Business CMS",
                price: "$599",
                features: [
                    "Everything in Starter CMS",
                    "Up to 10 Pages",
                    "Custom Theme Customization",
                    "Blog Setup",
                    "User-Friendly Admin Dashboard",
                    "Essential Plugin Configuration",
                    "Backup & Security Setup",
                    "Basic SEO Plugin Configuration",
                    "Performance Optimization",
                    "3 Rounds of Revisions",
                ],
            },
            {
                id: "cms-development-premium",
                sku: "CMS_DEVELOPMENT_PREMIUM",
                title: "Premium CMS",
                price: "$999",
                features: [
                    "Everything in Business CMS",
                    "Up to 20 Pages",
                    "Fully Customized CMS",
                    "E-Commerce Integration",
                    "Payment Gateway Integration",
                    "Booking or Appointment System",
                    "Membership or User Registration",
                    "Advanced Forms & Dynamic Content",
                    "Advanced Security & Performance Optimization",
                    "5 Rounds of Revisions",
                ],
            },
        ],
    },
    {
        id: "web-application-development",
        label: "Web Application Development",
        packages: [
            {
                id: "web-app-starter",
                sku: "WEB APP STARTER",
                title: "Starter Web App",
                price: "$999",
                features: [
                    "Custom Web Application",
                    "Up to 5 Core Screens",
                    "User Authentication (Login & Registration)",
                    "Responsive Design",
                    "Basic Dashboard",
                    "Contact/Inquiry Forms",
                    "Database Integration",
                    "Basic Security",
                    "Testing & Bug Fixes",
                    "2 Rounds of Revisions",
                    "Delivery in 2–3 Weeks",
                ],
            },
            {
                id: "web-app-business",
                sku: "WEB_APP_BUSINESS",
                title: "Business Web App",
                price: "$2,499",
                features: [
                    "Everything in Starter Web App",
                    "Up to 10 Core Screens",
                    "Admin Dashboard",
                    "User Roles & Permissions",
                    "Advanced Database Design",
                    "REST API Integration",
                    "File Upload Functionality",
                    "Email Notifications",
                    "Reports & Analytics",
                    "Performance Optimization",
                    "4 Rounds of Revisions",
                    "Delivery in 4–6 Weeks",
                ],
            },
            {
                id: "web-app-enterprise",
                sku: "WEB_APP_ENTERPRISE",
                title: "Enterprise Web App",
                price: "$4,999+",
                features: [
                    "Everything in Business Web App",
                    "Unlimited Core Screens",
                    "Custom Admin Panel",
                    "Advanced User Management",
                    "Third-Party API Integrations",
                    "Payment Gateway Integration",
                    "Real-Time Features",
                    "Advanced Security & Data Protection",
                    "Scalable Architecture",
                    "Deployment Assistance",
                    "Documentation",
                    "Priority Support During Development",
                    "6 Rounds of Revisions",
                    "Delivery Timeline Based on Project Scope",
                ],
            },
        ],
    },

    {
        id: "logo-design",
        label: "Logo Design",
        packages: [
            {
                id: "logo-design-basic",
                sku: "VIDEO TEASER",
                title: "Logo Basic",
                price: "$29",
                features: [
                    "4 Original Logo Concepts",
                    "2 Dedicated Logo Designer",
                    "4 Revisions",
                    "With Grey Scale Format",
                    "Free Icon Design",
                    "Formats: JPEG Only",
                    "24 - 48 Hours Turn Around Time",
                    "MORE FEATURES",
                    "100% Satisfaction",
                    "100% Ownership Rights",
                    "Money Back Guarantee",
                    "Dedicated Account Manager",
                ],
            },
            {
                id: "logo-design-silver",
                sku: "VIDEO_STARTUP",
                title: "Logo Silver",
                price: "$89",
                features: [
                    "6 Custom Logo Design Concepts",
                    "By 2 Designers",
                    "UNLIMITED Revisions",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "48 to 72 hours TAT",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                    "100% Ownership Rights *",
                    "100% Money Back Guarantee *",
                ],
            },
            {
                id: "logo-design-gold",
                sku: "VIDEO_CLASSIC",
                title: "Logo Gold",
                price: "$129",
                features: [
                    "12 Logo Design Concepts",
                    "By 4 Designers",
                    "UNLIMITED Revisions",
                    "Stationery Design (Business Card, Letterhead, Envelope)",
                    "FREE MS Word Letterhead",
                    "48 to 72 hours TAT",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                    "100% Ownership Rights *",
                    "100% Money Back Guarantee *",
                ],
            },
            {
                id: "logo-design-platinum",
                sku: "VIDEO_PREMIUM",
                title: "Logo Platinum",
                price: "$179",
                features: [
                    "UNLIMITED Logo Design Concepts",
                    "By 5 Award Winning Designers",
                    "Stationary Design (Business Card, Letterhead, Envelope)",
                    "FREE Social Media Banners (Any 2)",
                    "UNLIMITED Revisions",
                    "FREE MS Word Letterhead",
                    "Free Email Signature",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                    "100% Ownership Rights *",
                    "100% Money Back Guarantee *",
                    "48 to 72 hours TAT",
                ],
            },
            {
                id: "logo-design-elite",
                sku: "WEB_DESIGN_DELUXE",
                title: "Logo Elite Package",
                price: "$299",
                features: [
                    "You will get unlimited concepts by 10 designers",
                    "Unlimited Rounds of Changes",
                    "100% ownership rights",
                    "Turn Around time will be 24-48 hours",
                    "Icon design (Free)",
                    "500 Business Cards",
                    "You will get all the formats in HI-RES",
                    "You will be getting vector file",
                    "The Editable Vector Version (resizable)",
                    "You will be getting the Greyscale file (to be placed at any colored back ground)",
                    "You will be getting the Solid Black and Solid White version of the Logo (can be used for T-Shirts and Merchandise)",
                    "You will be getting the Colored Version with transparent background (can be used for stationery, merchandise, car wraps, sign boards, labelling, ETC)",
                    "You will be getting stationery designs (Business Cards, Letterheads, Envelops)",
                    "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
                    "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
                ],
            },
            {
                id: "logo-design-the-boss",
                sku: "WEB_DESIGN_DELUXE",
                title: "THE BOSS",
                price: "$599",
                features: [
                    "3D/Mascot/Animated Logo",
                    "Unlimited Original Logo Concepts",
                    "8 Dedicated Logo Designers (Industry-specific)",
                    "Unlimited Rounds Of Revisions",
                    "Stationery Design (Business Card, Letterhead, Envelope)",
                    "500 Business Cards",
                    "Email Signature Design",
                    "Free Icon Design",
                    "Grey Scale Format Attached",
                    "JPEG, PSD, EPS, AI, PNG, TIFF, SVG Formats",
                    "Turnaround Time Of 24-48 Hours",
                    "100% Satisfaction Guaranteed",
                    "100% Ownership Rights",
                    "Money-back Guarantee",
                    "Dedicated Account Manager",
                ],
            },
        ],
    },
    {
        id: "illustration",
        label: "Illustration",
        packages: [
            {
                id: "illustration-basic",
                sku: "BASIC ECOMMERCE PACKAGE",
                title: "BASIC",
                price: "$284",
                features: [
                    "3 Custom Logo Design Concepts",
                    "By 2 Designers",
                    "UNLIMITED Revisions",
                    "48 to 72 hours TAT",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "100% Ownership Rights",
                    "100% Satisfaction Guarantee",
                    "100% Money Back Guarantee *",
                    "*NO MONTHLY OR ANY HIDDEN FEE*",
                ],
            },
            {
                id: "illustration-startup",
                sku: "ECOMMERCE BEGINNERS",
                title: "START UP",
                price: "$394",
                features: [
                    "4 Custom Design Concepts",
                    "By 3 Designers",
                    "UNLIMITED Revisions",
                    "48 to 72 hours TAT",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "100% Ownership Rights",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                    "100% Money Back Guarantee *",
                ],
            },
            {
                id: "illustration-professional",
                sku: "PROFESSIONAL ECOMMERCE PACKAGE",
                title: "PROFESSIONAL",
                price: "$594",
                features: [
                    "UNLIMITED Design Concepts",
                    "By 4 Designers",
                    "UNLIMITED Revisions",
                    "24 to 48 hours TAT",
                    "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
                    "Dedicated Project Manager",
                    "100% Ownership Rights",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                    "100% Money Back Guarantee *",
                ],
            },
        ],
    },
    {
        id: "combo",
        label: "Combo",
        packages: [
            {
                id: "combo-startup",
                sku: "COMBO BASIC COMBO",
                title: "STARTUP",
                price: "$799",
                features: [
                    "4 Logo Design Concepts",
                    "4 Dedicated Designers",
                    "Icon Design",
                    "Website Pages",
                    "Conceptual and Dynamic Website",
                    "Content Management System (CMS)",
                    "Custom Forms",
                    "Lead Capturing Forms (Optional)",
                    "Newsfeed Integration",
                    "Social Media Integration",
                    "Search Engine Submission",
                    "6 Unique Banner Designs",
                    "jQuery Slider",
                    "Free Google Friendly Sitemap",
                    "All Final File Formats",
                    "Dedicated Account Manager",
                    "100% Ownership",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                ],
            },
            {
                id: "combo-economy",
                sku: "COMBO STARTUP COMBO",
                title: "ECONOMY",
                price: "$1119",
                features: [
                    "6 Logo Design Concepts",
                    "+ Social Media Design",
                    "Mobile Responsive",
                    "6 Dedicated Designers",
                    "Icon Design",
                    "Business Card, Letterhead, Envelope",
                    "MS Word Letterhead",
                    "Website Pages",
                    "Content Management System (CMS)",
                    "5 Stock Photos + 3 Banner Designs",
                    "Complete W3C Certified HTML",
                    "Complete Deployment",
                    "Facebook Page Design",
                    "All Final File Formats",
                    "Dedicated Account Manager",
                    "100% Ownership",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                ],
            },
            {
                id: "combo-corporate",
                sku: "COMBO PROFESSIONAL COMBO",
                title: "CORPORATE",
                price: "$1594",
                features: [
                    "Complete Custom Design & Development",
                    "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
                    "Banner Designs",
                    "JQuery Slider",
                    "Special Hoover Effects",
                    "Stock Images",
                    "Client/User Dashboard Area",
                    "Online Payment Integration (Optional)",
                    "Custom Dynamic Forms (Optional)",
                    "User Signup Area",
                    "User Login Area",
                    "User Dashboard Area",
                    "Complete Database Creation",
                    "Signup Automated Email Authentication",
                    "Web Traffic Analytics Integration",
                    "Signup Area (For Newsletters, Offers etc.)",
                    "Search Bar for Easy Search",
                    "Search Engine Submission",
                    "Module-wise Architecture",
                    "Extensive Admin Panel",
                    "Award Winning Team of Expert Designers and Developers",
                    "Complete Deployment",
                    "100% Satisfaction Guarantee",
                    "100% Unique Design Guarantee",
                ],
            },
        ],
    },
    {
        id: "marketing-collateral",
        label: "Marketing Collateral",
        packages: [
            {
                id: "marketing-collateral-startup",
                sku: "WEB CONTENT",
                title: "STARTUP",
                price: "$99",
                features: [
                    "2 Stationery Design Set",
                    "FREE Fax Template",
                    "Print Ready Formats",
                    "UNLIMITED Revisions",
                    "100% Satisfaction Guarantee",
                    "100% Money Back Guarantee *",
                ],
            },
            {
                id: "marketing-collateral-classic",
                sku: "Article Writing",
                title: "CLASSIC",
                price: "$199",
                features: [
                    "2 Stationery Design Set",
                    "UNLIMITED Revisions",
                    "Flyer Design",
                    "Brochure Design (Bi-fold/Tri-fold)",
                    "100% Satisfaction Guarantee",
                    "100% Money Back Guarantee *",
                ],
            },
            {
                id: "marketing-collateral-premium",
                sku: "Creative Writing",
                title: "PREMIUM",
                price: "$399",
                features: [
                    "2 Stationery Design Set",
                    "Packaging Design",
                    "UNLIMITED Revisions",
                    "T-Shirt Design",
                    "100% Satisfaction Guarantee",
                    "100% Money Back Guarantee *",
                ],
            },
        ],
    },
    {
        id: "seo",
        label: "SEO",
        packages: [
            {
                id: "seo-starter",
                sku: "STARTER SEO PLAN",
                title: "STARTER",
                price: "$199/Month",
                features: [
                    "Website SEO Audit",
                    "Keyword Research (Up to 10 Keywords)",
                    "On-Page SEO Optimization",
                    "Meta Titles & Descriptions",
                    "Image Optimization",
                    "XML Sitemap & Robots.txt Review",
                    "Google Search Console Setup",
                    "Monthly Performance Report",
                ],
            },
            {
                id: "seo-business",
                sku: "BUSINESS SEO PLAN",
                title: "BUSINESS",
                price: "$499/Month",
                features: [
                    "Everything in Starter SEO",
                    "Keyword Research (Up to 30 Keywords)",
                    "Technical SEO Optimization",
                    "Internal Linking Strategy",
                    "Content Optimization",
                    "Local SEO",
                    "Competitor Analysis",
                    "Basic Link Building",
                    "Monthly SEO Strategy Updates",
                    "Detailed Monthly Reporting",
                ],
            },
            {
                id: "seo-premium",
                sku: "PREMIUM SEO PLAN",
                title: "PREMIUM",
                price: "$999/Month",
                features: [
                    "Everything in Business SEO",
                    "Keyword Research (Up to 50 Keywords)",
                    "Advanced Technical SEO",
                    "SEO Strategy & Competitor Monitoring",
                    "High-Quality Link Building",
                    "SEO-Optimized Internal Blog Writing",
                    "SEO Optimization for Service & Product Pages",
                    "Content Strategy & On-Page Content Optimization",
                    "Priority Support",
                    "Ongoing SEO Consultation",
                ],
            },
        ],
    },
    {
        id: "creative-copywriting",
        label: "Creative Copywriting",
        packages: [
            {
                id: "creative-copywriting-basic",
                sku: "Starter",
                title: "BASIC",
                price: "$129",
                features: [
                    "1 Page Professional Copywriting Service",
                    "Creative & Well-Written by 1 Professional Copywriter",
                    "Industry Specified Expert Copywriter",
                    "300 Words Per Page",
                    "5 Revisions",
                    "3 to 4 Business Days Rotation",
                    "According To Your Exact Requirements",
                    "Proofing by our in-house experts",
                    "100% Ownership Rights",
                    "100% Original Content",
                    "100% Approval Assurance",
                    "30 Days Refund Warranty *",
                ],
            },
            {
                id: "creative-copywriting-blog-writing",
                sku: "Professional",
                title: "BLOG WRITING",
                price: "$129",
                features: [
                    "1 Creative, Fresh & Well-Written Blog",
                    "By 1 Professional Blogwriter",
                    "Industry Specified Expert Blogwriter",
                    "300-500 Words Per Page",
                    "3 to 5 Business Days Rotation",
                    "5 Revisions",
                    "According To Your Exact Requirements",
                    "Written on Your Specified Topic/Keyword",
                    "Proofing by our in-house experts",
                    "Free Submission on any article marketing directories /blog (If required)",
                    "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
                    "100% Ownership Rights",
                    "100% Original Content",
                    "100% Approval Assurance",
                    "30 Days Refund Warranty *",
                ],
            },
            {
                id: "creative-copywriting-article",
                sku: "Business",
                title: "ARTICLE",
                price: "$149",
                features: [
                    "1 Creative, Fresh & Well-Written Article",
                    "By 1 Professional Copywriter",
                    "Industry Specified Expert Copywriter",
                    "400 Words Per Page",
                    "3 to 5 Business Days Rotation",
                    "5 Revisions",
                    "According To Your Exact Requirements",
                    "Written on Your Specified Topic/Keyword",
                    "Proofing by our in-house experts",
                    "Free Submission on any article marketing directories /blog (If required)",
                    "SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner",
                    "100% Ownership Rights",
                    "100% Original Content",
                    "100% Approval Assurance",
                    "30 Days Refund Warranty *",
                ],
            },
        ],
    },
    {
        id: "mobile-app",
        label: "Mobile App",
        packages: [
            {
                id: "mobile-app-starter",
                sku: "STARTER APP PLAN",
                title: "STARTER",
                price: "$1,499",
                features: [
                    "Android or iOS App",
                    "Up to 5 Screens",
                    "Custom UI Design",
                    "User Registration & Login",
                    "Basic Database Integration",
                    "Push Notifications",
                    "API Integration",
                    "Testing & Bug Fixes",
                    "2 Rounds of Revisions",
                ],
            },
            {
                id: "mobile-app-business",
                sku: "BUSINESS APP PLAN",
                title: "BUSINESS",
                price: "$3,499",
                features: [
                    "Everything in Starter App",
                    "Android & iOS Apps",
                    "Up to 10 Screens",
                    "Admin Dashboard",
                    "User Roles & Permissions",
                    "Advanced API Integrations",
                    "In-App Search & Filters",
                    "File Upload Functionality",
                    "Analytics Integration",
                    "Performance Optimization",
                    "4 Rounds of Revisions",
                ],
            },
            {
                id: "mobile-app-enterprise",
                sku: "ENTERPRISE APP PLAN",
                title: "ENTERPRISE",
                price: "$6,999+",
                features: [
                    "Everything in Business App",
                    "Unlimited Screens",
                    "Custom UI/UX Design",
                    "Payment Gateway Integration",
                    "Real-Time Chat & Notifications",
                    "Location & Maps Integration",
                    "Subscription & Membership Features",
                    "Advanced Security & Data Encryption",
                    "Backend Integration",
                    "Documentation & Training",
                    "Priority Support",
                    "6 Rounds of Revisions",
                    "Timeline Based on Project Scope",
                ],
            },
        ],
    },
];